# Generated by Django 4.2.7 on 2024-01-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_service2_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
